PROBLEM='Problem'
TIME='time'
CPU_TIME_USER='CPU user'
CPU_TIME_SYS='CPU sys'
RESULT = 'result'
STATUS = 'status'
ERROR = 'error'
ICP_TIME = "ICP time"
TESTING_TIME = "Testing time"
DECOMP_TIME = "Decomp time"
REDUCE_TIME = "Reduce time"
IVT_TIME = "IVT time"

HEADERS = [PROBLEM, STATUS, RESULT, TIME, CPU_TIME_USER, CPU_TIME_SYS, ICP_TIME, TESTING_TIME, IVT_TIME, DECOMP_TIME, REDUCE_TIME]

MAX_MEMORY = "MAX_MEMORY"
TIMEOUT = "TIMEOUT"
WALL_TIMEOUT = "WALL_TIMEOUT"
TOOL = "TOOL"
FLAGS = "FLAGS"
TOOL_COMMAND = "TOOL_COMMAND"
RESULT_FILE = "RESULT_FILE"